name: Terraform Destroy
on:
  workflow_dispatch:
jobs:
  terraform-plan:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
        TF_VAR_region: "eu-west-2"
        TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        TFSTATE_AWS_ACCESS_KEY_ID: ${{ secrets.TFSTATE_AWS_ACCESS_KEY_ID }}
        TFSTATE_AWS_SECRET_ACCESS_KEY: ${{ secrets.TFSTATE_AWS_SECRET_ACCESS_KEY }}
        TFSTATE_BUCKET: "travelperk-devops-assessment"
        TFSTATE_KEY: "terraform.tfstate"
        TFSTATE_REGION: "eu-west-2"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.4
    - name: Terraform Init
      run: terraform init -backend-config="bucket=$TFSTATE_BUCKET" -backend-config="key=$TFSTATE_KEY" -backend-config="region=$TFSTATE_REGION" -backend-config="access_key=${{ secrets.TFSTATE_AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.TFSTATE_AWS_SECRET_ACCESS_KEY }}"
      working-directory: ./terraform
    - name: Terraform Plan
      run: terraform plan -destroy -out=tfplandestroy
      working-directory: ./terraform
    - name: Terraform Apply
      run: terraform apply tfplandestroy
      working-directory: ./terraform