name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Replace with your desired Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: terraform apply tfplan
      env:
        TF_VAR_region: "eu-west-2"  # Replace with your desired AWS region
        TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Note: Make sure to set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY secrets in your GitHub repository.
